Restaurant.create!(name: 'chez Roro', address: '28 rue la bas', category: 'french')
Restaurant.create!(name: 'le fieu', address: 'ici gros', category: 'belgian')
Restaurant.create!(name: 'Osaka', address: 'pas loin du wagon', category: 'japanese')
Restaurant.create!(name: 'Nouillecademy', address: 'Vers la grande église', category: 'chinese')
Restaurant.create!(name: 'La cucina de la nona', address: 'chez mémé', category: 'italian')
